/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesManagerRole;

import Business.Customer;
import Business.CustomerDirectory;
import Business.Employee;
import Business.EmployeeDirectory;
import Business.MasterOrderCatalog;
import Business.Order;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raghuram
 */
public class ManageCustomers extends javax.swing.JPanel {

    private Employee employee;
    private JPanel userProcessContainer;
    private SupplierDirectory supplierDirectory;
    private MasterOrderCatalog moc;
    private Order order;

    /**
     * Creates new form ManageCustomers
     */
    public ManageCustomers(Employee employee,SupplierDirectory supplierDirectory, MasterOrderCatalog moc, Order order, JPanel userProcessContainer) {
        initComponents();
        this.employee = employee;
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
        this.moc = moc;
        this.order = order;
        txtEName.setText(employee.getEmployeeName());
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) customerTable.getModel();
        dtm.setRowCount(0);
        for (Customer c : employee.getCustomerDirectory().getCustomerList()) {
            Object row[] = new Object[3];
            row[0] = c;
            row[1] = c.getCustomerID();
            row[2] = c.getCustomerPhone();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteCustomer = new javax.swing.JButton();
        btnEnterCustomer = new javax.swing.JButton();
        btnViewCustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtEName = new javax.swing.JTextField();
        btnServeCustomer = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        btnSalesCommision = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeleteCustomer.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnDeleteCustomer.setText("Delete Customer Details");
        btnDeleteCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });
        add(btnDeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 220, 30));

        btnEnterCustomer.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnEnterCustomer.setText("Enter Customer Details");
        btnEnterCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEnterCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterCustomerActionPerformed(evt);
            }
        });
        add(btnEnterCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 30));

        btnViewCustomer.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnViewCustomer.setText("View Customer Details");
        btnViewCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerActionPerformed(evt);
            }
        });
        add(btnViewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 220, 30));

        customerTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Customer ID", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 480, 110));

        btnBack.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Employee:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, -1));

        txtEName.setEditable(false);
        txtEName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtENameActionPerformed(evt);
            }
        });
        add(txtEName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 30));

        btnServeCustomer.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnServeCustomer.setText("Serve Customer>>");
        btnServeCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnServeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomerActionPerformed(evt);
            }
        });
        add(btnServeCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 210, 30));

        btnOrderHistory.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnOrderHistory.setText("Review Sales Order History>>");
        btnOrderHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });
        add(btnOrderHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 210, 30));

        btnSalesCommision.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnSalesCommision.setText("Review Sales Comission>>");
        btnSalesCommision.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalesCommision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesCommisionActionPerformed(evt);
            }
        });
        add(btnSalesCommision, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a customer from the table!!!", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete Customer", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Customer c = (Customer) customerTable.getValueAt(selectedRow, 0);
                employee.getCustomerDirectory().deleteCustomer(c);

                populateTable();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnEnterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterCustomerActionPerformed
        CreateCustomerJPanel ccj = new CreateCustomerJPanel(employee.getCustomerDirectory(), userProcessContainer);
        userProcessContainer.add("ccj", ccj);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterCustomerActionPerformed

    private void btnViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerActionPerformed

        int row = customerTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Customer from the table",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Customer customer = (Customer) customerTable.getValueAt(row, 0);
        ViewCustomerJPanel VCJ = new ViewCustomerJPanel(customer, userProcessContainer);
        userProcessContainer.add("VCJ", VCJ);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCustomerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtENameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtENameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtENameActionPerformed

    private void btnServeCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomerActionPerformed
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a customer from the table!!!", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ServeCustomer sc = new ServeCustomer(employee,supplierDirectory,moc,order,userProcessContainer);
            userProcessContainer.add("sc", sc);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
// TODO add your handling code here:
    }//GEN-LAST:event_btnServeCustomerActionPerformed
    }
    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        ReviewSalesOrderHistory sc = new ReviewSalesOrderHistory(userProcessContainer);
        userProcessContainer.add("sc", sc);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderHistoryActionPerformed

    private void btnSalesCommisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesCommisionActionPerformed
        ReviewSalesComission sc = new ReviewSalesComission(userProcessContainer);
        userProcessContainer.add("sc", sc);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalesCommisionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnEnterCustomer;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnSalesCommision;
    private javax.swing.JButton btnServeCustomer;
    private javax.swing.JButton btnViewCustomer;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEName;
    // End of variables declaration//GEN-END:variables
}
