/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesManagerRole;

import Business.Employee;
import Business.EmployeeDirectory;
import Business.MasterOrderCatalog;
import Business.Order;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Raghuram
 */
public class ServeCustomer extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Employee employee;
    private SupplierDirectory supplierDirectory;
    private MasterOrderCatalog moc;
    private Order order;

    /**
     * Creates new form ServeCustomer
     */
    public ServeCustomer(Employee employee,SupplierDirectory supplierDirectory,MasterOrderCatalog moc,Order order,JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.employee = employee;
        this.supplierDirectory = supplierDirectory;
        this.moc = moc;
        this.order = order;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnBookOrder = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 70, -1));

        btnBookOrder.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnBookOrder.setText("Book Customer Order");
        btnBookOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBookOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookOrderActionPerformed(evt);
            }
        });
        add(btnBookOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookOrderActionPerformed
        BookCustomerOrder bco = new BookCustomerOrder(employee,supplierDirectory,moc,order,userProcessContainer);
        userProcessContainer.add("bco", bco);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookOrder;
    // End of variables declaration//GEN-END:variables
}
