/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesManagerRole;

import Business.Customer;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Raghuram
 */
public class ViewCustomerJPanel extends javax.swing.JFrame {
private Customer customer;
private JPanel userProcessContainer;
    /**
     * Creates new form ViewCustomerJPanel
     */
    public ViewCustomerJPanel(Customer customer, JPanel userProcessContainer) {
        initComponents();            
        this.customer = customer;
        this.userProcessContainer = userProcessContainer;
        txtCName.setText(customer.getCustomerName());
        txtCID.setText(customer.getCustomerID());
        txtCPhone.setText(String.valueOf(customer.getCustomerPhone()));
        txtCEmail.setText(customer.getAddress());
        txtCAddress.setText(customer.getEmail());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUpdateStore = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("VIEW CUSTOMER DETAILS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        btnUpdateStore.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        btnUpdateStore.setText("Update Store");
        btnUpdateStore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdateStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStoreActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 100, 30));

        btnBack.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 30));

        btnSave.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 50, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Customer Phone");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 20));

        txtCPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtCPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Email ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 20));

        txtCEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtCEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 20));

        txtCAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtCAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Customer Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        txtCName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtCName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Customer ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 20));

        txtCID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStoreActionPerformed

        txtCName.setEnabled(true);
        txtCID.setEnabled(true);
        txtCAddress.setEnabled(true);
        txtCEmail.setEnabled(true);
        txtCPhone.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdateStore.setEnabled(false);
    }//GEN-LAST:event_btnUpdateStoreActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back();

        }

        private void back() {
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component manageCustomers = componentArray[componentArray.length - 1];
            ManageCustomers manage = (ManageCustomers) manageCustomers;
            manage.populateTable();
            CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
            Layout.previous(userProcessContainer);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtCName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Customer name");
            return;
        } else if (txtCID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Customer ID");
            return;
        } else if (txtCEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Customer Email ID");
            return;

        } else if (txtCAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Customer Address");
            return;
        } else if (!txtCPhone.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Enter a valid Phone Number");
            return;
        }
        try {
            customer.setCustomerName(txtCName.getText());
            customer.setCustomerID(txtCID.getText());
            customer.setEmail(txtCEmail.getText());
            customer.setAddress(txtCAddress.getText());
            customer.setCustomerPhone(Integer.parseInt(txtCPhone.getText()));

            JOptionPane.showMessageDialog(null, "Store Details saved successfully",
                "Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to save store details",
                "Warning", JOptionPane.WARNING_MESSAGE);
        } finally {
            txtCName.setEditable(false);

            txtCID.setEditable(false);
            txtCEmail.setEditable(false);
            txtCAddress.setEditable(false);
            txtCPhone.setEditable(false);
            btnSave.setEnabled(false);
            btnUpdateStore.setEnabled(true);

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateStore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCAddress;
    private javax.swing.JTextField txtCEmail;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCPhone;
    // End of variables declaration//GEN-END:variables
}
