/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface_CVSAdminRole;

/**
 *
 * @author Raghuram
 */
public class CreateCVSStoresJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCVSStoresJPanel
     */
    public CreateCVSStoresJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        txtSID = new javax.swing.JTextField();
        txtSLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSZipcode = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CVS Stores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setText("Store Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 20));

        jLabel3.setText("Store ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 20));

        jLabel4.setText("Location");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));
        add(txtSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, -1));
        add(txtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, -1));
        add(txtSLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 100, -1));

        jLabel5.setText("Zip Code");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 20));
        add(txtSZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, -1));

        btnCreate.setText("Create");
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSLocation;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSZipcode;
    // End of variables declaration//GEN-END:variables
}
