/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface_CVSAdminRole;

import Business.Drug;
import Business.Store;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raghuram
 */
public class ViewCVSStoresJPanel extends javax.swing.JPanel {

    private Store store;
    private JPanel userProcessContainer;

    /**
     * Creates new form ViewCVSStoresJPanel
     */
    public ViewCVSStoresJPanel(Store store, JPanel userProcessContainer) {
        initComponents();
        this.store = store;
        this.userProcessContainer = userProcessContainer;
        txtSName.setText(store.getStoreName());
        txtSID.setText(store.getStoreID());
        txtSManager.setText(store.getStoreManager());
        txtSLocation.setText(store.getStoreLocation());
        txtSZipcode.setText(String.valueOf(store.getZipcode()));
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) drugTable.getModel();
        dtm.setRowCount(0);
        for (Drug d : store.getDrugCatalog().getDrugList()) {
            Object row[] = new Object[3];
            row[0] = d;
            row[1] = d.getDrugID();
            row[2] = d.getDrugPrice();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnUpdateStore = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        txtSID = new javax.swing.JTextField();
        txtSLocation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSZipcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSManager = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("View Store");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        btnUpdateStore.setText("Update Store");
        btnUpdateStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStoreActionPerformed(evt);
            }
        });
        add(btnUpdateStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel3.setText("Store Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jLabel4.setText("Store ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel5.setText("Location");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        txtSName.setEnabled(false);
        add(txtSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, -1));

        txtSID.setEnabled(false);
        add(txtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, -1));

        txtSLocation.setEnabled(false);
        add(txtSLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, -1));

        jLabel6.setText("Zip Code");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        txtSZipcode.setEnabled(false);
        add(txtSZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, -1));

        jLabel7.setText("Store Manager");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        txtSManager.setEnabled(false);
        add(txtSManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 100, -1));

        drugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Drug ID", "Drug Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(drugTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 320, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStoreActionPerformed

        txtSName.setEnabled(true);
        txtSID.setEnabled(true);
        txtSLocation.setEnabled(true);
        txtSManager.setEnabled(true);
        txtSZipcode.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdateStore.setEnabled(false);
    }//GEN-LAST:event_btnUpdateStoreActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back();

    }

    private void back() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component manageCVSStoresJPanel = componentArray[componentArray.length - 1];
        ManageCVSStoresJPanel manage = (ManageCVSStoresJPanel) manageCVSStoresJPanel;
        manage.populateTable();
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtSName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Store name");
            return;
        } else if (txtSID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Store ID");
            return;
        } else if (txtSLocation.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Store Location");
            return;

        } else if (txtSManager.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid store Manager");
            return;
        } else if (!txtSZipcode.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Enter a valid zipcode");
            return;
        }
        try {
            store.setStoreName(txtSName.getText());
            store.setStoreID(txtSID.getText());
            store.setStoreLocation(txtSLocation.getText());
            store.setStoreManager(txtSManager.getText());
            store.setZipcode(Integer.parseInt(txtSZipcode.getText()));

            JOptionPane.showMessageDialog(null, "Store Details saved successfully",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to save store details",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } finally {
            txtSName.setEditable(false);

            txtSID.setEditable(false);
            txtSLocation.setEditable(false);
            txtSManager.setEditable(false);
            txtSZipcode.setEditable(false);
            btnSave.setEnabled(false);
            btnUpdateStore.setEnabled(true);

        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateStore;
    private javax.swing.JTable drugTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSLocation;
    private javax.swing.JTextField txtSManager;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSZipcode;
    // End of variables declaration//GEN-END:variables
}
