/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Raghuram
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    private Person person;
    private JPanel userProcessContainer;

    /**
     * Creates new form CreatePatientJpanel
     */
    public CreatePatientJPanel(Person person, JPanel userProcessContainer) {
        initComponents();
        this.person = person;
        this.userProcessContainer = userProcessContainer;
        txtName.setText(person.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientID = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        btnCreatePatient = new javax.swing.JButton();
        txtPatientId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblPharmacy = new javax.swing.JLabel();
        txtDoctor = new javax.swing.JTextField();
        txtPharmacy = new javax.swing.JTextField();
        lblPatientID1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPatientID.setText("Patient ID");
        add(lblPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        lblDoctor.setText("Primary Doctor Name");
        add(lblDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        btnCreatePatient.setText("Create ");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });
        add(btnCreatePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        txtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIdActionPerformed(evt);
            }
        });
        add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CREATE PATIENT");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        lblPharmacy.setText("Preferred Pharmacy");
        add(lblPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        txtDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorActionPerformed(evt);
            }
        });
        add(txtDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 110, -1));

        txtPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharmacyActionPerformed(evt);
            }
        });
        add(txtPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 110, -1));

        lblPatientID1.setText("Patient Name");
        add(lblPatientID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        if (txtPatientId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter the Patient ID");
            return;

        } else if (txtDoctor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter the Doctor's name");
            return;
        } else if (txtPharmacy.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter the Preferred pharmacy");
            return;
        }
        person.getPatient().setPatientId(txtPatientId.getText());
        person.getPatient().setDoctorName(txtDoctor.getText());
        person.getPatient().setPharmacy(txtPharmacy.getText());
        JOptionPane.showMessageDialog(null, "Patient details for " + person.getName() + " has been created", "Information", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void txtPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIdActionPerformed

    private void txtDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorActionPerformed

    private void txtPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharmacyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPharmacyActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientID1;
    private javax.swing.JLabel lblPharmacy;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPharmacy;
    // End of variables declaration//GEN-END:variables
}
