/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Patient;
import Business.Person;
import Business.PersonDirectory;
import Business.VitalSign;
import Business.VitalSignHistory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raghuram
 */
public class ViewVitalSignJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Person person;
    private String result;

    /**
     * Creates new form ViewVitalSignJPanel
     */
    public ViewVitalSignJPanel(Person person, JPanel userProcessContainer) {
        initComponents();
        this.person = person;
        this.userProcessContainer = userProcessContainer;

        populateTable();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblVitalSign.getModel();
        //int rowCount = tblVitalSign.getRowCount();
        /*for(int i= rowCount-1;i>=0;i--){
         dtm.removeRow(i);
         }*/
        dtm.setRowCount(0);
        VitalSignHistory vitalSignHistory = person.getPatient().getVitalSignHistory();
        for (VitalSign vs : vitalSignHistory.getVitalSignList()) {
            /*if((patient.getAge()>=1&& patient.getAge()<=3)){
             if((vs.getRespiratoryRate()>=20&& vs.getRespiratoryRate()<=30)
             &&(vs.getHeartRate()>=80&& vs.getHeartRate()<=130)
             &&(vs.getBloodPressure()>=80&& vs.getBloodPressure()<=110)
             &&(vs.getWeight()>=22&& vs.getWeight()<=31))
             {
             result = "normal";
             }
             }*/

            if ((person.getAge() >= 1 && person.getAge() <= 3) && (vs.getRespiratoryRate() >= 20 && vs.getRespiratoryRate() <= 30)
                    && (vs.getHeartRate() >= 80 && vs.getHeartRate() <= 130)
                    && (vs.getBloodPressure() >= 80 && vs.getBloodPressure() <= 110)
                    && (vs.getWeight() >= 22 && vs.getWeight() <= 31)) {
                result = "normal";
            } else if ((person.getAge() >= 4 && person.getAge() <= 5) && (vs.getRespiratoryRate() >= 20 && vs.getRespiratoryRate() <= 30)
                    && (vs.getHeartRate() >= 80 && vs.getHeartRate() <= 120)
                    && (vs.getBloodPressure() >= 80 && vs.getBloodPressure() <= 110)
                    && (vs.getWeight() >= 31 && vs.getWeight() <= 40)) {
                result = "normal";
            } else if ((person.getAge() >= 6 && person.getAge() <= 12) && (vs.getRespiratoryRate() > 20 && vs.getRespiratoryRate() < 30)
                    && (vs.getHeartRate() >= 70 && vs.getHeartRate() < 110)
                    && (vs.getBloodPressure() >= 80 && vs.getBloodPressure() <= 120)
                    && (vs.getWeight() >= 41 && vs.getWeight() <= 92)) {
                result = "normal";
            } else if ((person.getAge() >= 13) && (vs.getRespiratoryRate() >= 12 && vs.getRespiratoryRate() <= 20)
                    && (vs.getHeartRate() >= 55 && vs.getHeartRate() <= 105)
                    && (vs.getBloodPressure() >= 110 && vs.getBloodPressure() <= 120)
                    && (vs.getWeight() >= 110)) {
                result = "normal";
            } else {
                result = "abnormal";
            }

            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = result;

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSign = new javax.swing.JTable();
        lblRespiiratoryRate = new javax.swing.JLabel();
        txtRespiratoryRate = new javax.swing.JTextField();
        lblHeartRate = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        btnViewDetails = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVitalSign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time Stamp", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVitalSign);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 550, 179));

        lblRespiiratoryRate.setText("Respiratory Rate");
        add(lblRespiiratoryRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        txtRespiratoryRate.setEditable(false);
        txtRespiratoryRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespiratoryRateActionPerformed(evt);
            }
        });
        add(txtRespiratoryRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 110, -1));

        lblHeartRate.setText("Heart Rate");
        add(lblHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        lblBP.setText("Systolic Blood Pressure");
        add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        lblWeight.setText("Weight in pounds");
        add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        txtHeartRate.setEditable(false);
        txtHeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeartRateActionPerformed(evt);
            }
        });
        add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 110, -1));

        txtBP.setEditable(false);
        txtBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPActionPerformed(evt);
            }
        });
        add(txtBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 110, -1));

        txtWeight.setEditable(false);
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 110, -1));

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespiratoryRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespiratoryRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespiratoryRateActionPerformed

    private void txtHeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeartRateActionPerformed

    private void txtBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed

        int selectedRow = tblVitalSign.getSelectedRow();
        if (selectedRow >= 0) {
            VitalSign vs = (VitalSign) tblVitalSign.getValueAt(selectedRow, 0);
            txtRespiratoryRate.setText(String.valueOf(vs.getRespiratoryRate()));
            txtHeartRate.setText(String.valueOf(vs.getHeartRate()));
            txtBP.setText(String.valueOf(vs.getBloodPressure()));
            txtWeight.setText(String.valueOf(vs.getWeight()));

        } else {
            JOptionPane.showMessageDialog(null, "Please select an entry from the table", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblRespiiratoryRate;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTable tblVitalSign;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
