/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.NurseRoleJPanel.ProcessWorkRequestJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Raghuram
 */
public class ReceptionistWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;

    /**
     * Creates new form ReceptionistWorkAreaJPanel123
     */
    public ReceptionistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,
            Organization organization, Enterprise enterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        populateDonorCombo();
    }
    
    public void populateDonorCombo(){
        donorCombo.removeAllItems();
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            System.out.println("inside org");
            if(org instanceof DonorOrganization){
                System.out.println("inside donor");
                for(Employee employee : org.getEmployeeDirectory().getEmployeeList()){
                    System.out.println("inside employee");
                    donorCombo.addItem(employee);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWorkStatus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        donorCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWorkStatus.setText("Work Status");
        btnWorkStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkStatusActionPerformed(evt);
            }
        });
        add(btnWorkStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Reception Work Area ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        donorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorComboActionPerformed(evt);
            }
        });
        add(donorCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, -1));

        jLabel2.setText("Donor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 74, 40, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnWorkStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkStatusActionPerformed
        Employee emp = (Employee) donorCombo.getSelectedItem();
        WorkStatusJPanel workStatusJPanel = new WorkStatusJPanel(userProcessContainer, userAccount,organization,  enterprise, emp);
        userProcessContainer.add("workStatusJPanel", workStatusJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

// TODO add your handling code here:
    }//GEN-LAST:event_btnWorkStatusActionPerformed

    private void donorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWorkStatus;
    private javax.swing.JComboBox donorCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
