/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommunityUrbanHouseholdWorkArea;

import UserInterface.IndustryEmployeeWorkArea.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Raghuram
 */
public class SensorInputJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    /**
     * Creates new form PayEBillJPanel
     */
    public SensorInputJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        backJButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        heavySlider = new javax.swing.JSlider();
        lightSlider = new javax.swing.JSlider();
        mediumSlider1 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        heavySlider1 = new javax.swing.JSlider();
        mediumSlider2 = new javax.swing.JSlider();
        mediumSlider3 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mediumSlider4 = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        heavySlider3 = new javax.swing.JSlider();
        mediumSlider5 = new javax.swing.JSlider();
        mediumSlider6 = new javax.swing.JSlider();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SENSOR INPUT");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        submitJButton.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 90, 30));

        backJButton3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        backJButton3.setText("<< Back");
        backJButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });
        add(backJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 80, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setText("Light Duty Appliances");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel4.setText("Fridge");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel5.setText("Heater");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 40));

        heavySlider.setBackground(new java.awt.Color(255, 204, 102));
        heavySlider.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        heavySlider.setForeground(new java.awt.Color(0, 0, 102));
        heavySlider.setMajorTickSpacing(1000);
        heavySlider.setMaximum(5000);
        heavySlider.setMinimum(1000);
        heavySlider.setMinorTickSpacing(1000);
        heavySlider.setPaintLabels(true);
        heavySlider.setPaintTicks(true);
        heavySlider.setSnapToTicks(true);
        add(heavySlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 240, 40));

        lightSlider.setBackground(new java.awt.Color(255, 204, 102));
        lightSlider.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        lightSlider.setForeground(new java.awt.Color(0, 0, 102));
        lightSlider.setMajorTickSpacing(10);
        lightSlider.setMinorTickSpacing(10);
        lightSlider.setPaintLabels(true);
        lightSlider.setPaintTicks(true);
        lightSlider.setSnapToTicks(true);
        lightSlider.setValue(0);
        add(lightSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 240, 40));

        mediumSlider1.setBackground(new java.awt.Color(255, 204, 102));
        mediumSlider1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        mediumSlider1.setForeground(new java.awt.Color(0, 0, 102));
        mediumSlider1.setMajorTickSpacing(200);
        mediumSlider1.setMaximum(1000);
        mediumSlider1.setMinorTickSpacing(200);
        mediumSlider1.setPaintLabels(true);
        mediumSlider1.setPaintTicks(true);
        mediumSlider1.setSnapToTicks(true);
        add(mediumSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 240, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel6.setText("Television");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel7.setText("Blender");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel8.setText("Computer");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, 40));

        heavySlider1.setBackground(new java.awt.Color(255, 204, 102));
        heavySlider1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        heavySlider1.setForeground(new java.awt.Color(0, 0, 102));
        heavySlider1.setMajorTickSpacing(1000);
        heavySlider1.setMaximum(5000);
        heavySlider1.setMinimum(1000);
        heavySlider1.setMinorTickSpacing(1000);
        heavySlider1.setPaintLabels(true);
        heavySlider1.setPaintTicks(true);
        heavySlider1.setSnapToTicks(true);
        add(heavySlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 240, 40));

        mediumSlider2.setBackground(new java.awt.Color(255, 204, 102));
        mediumSlider2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        mediumSlider2.setForeground(new java.awt.Color(0, 0, 102));
        mediumSlider2.setMajorTickSpacing(200);
        mediumSlider2.setMaximum(1000);
        mediumSlider2.setMinorTickSpacing(200);
        mediumSlider2.setPaintLabels(true);
        mediumSlider2.setPaintTicks(true);
        mediumSlider2.setSnapToTicks(true);
        add(mediumSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 240, 40));

        mediumSlider3.setBackground(new java.awt.Color(255, 204, 102));
        mediumSlider3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        mediumSlider3.setForeground(new java.awt.Color(0, 0, 102));
        mediumSlider3.setMajorTickSpacing(200);
        mediumSlider3.setMaximum(1000);
        mediumSlider3.setMinorTickSpacing(200);
        mediumSlider3.setPaintLabels(true);
        mediumSlider3.setPaintTicks(true);
        mediumSlider3.setSnapToTicks(true);
        add(mediumSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 240, 40));

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel9.setText("Oven");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 40));

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel10.setText("Other Pluggable Appliances");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, 40));

        mediumSlider4.setBackground(new java.awt.Color(255, 204, 102));
        mediumSlider4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        mediumSlider4.setForeground(new java.awt.Color(0, 0, 102));
        mediumSlider4.setMajorTickSpacing(200);
        mediumSlider4.setMaximum(1000);
        mediumSlider4.setMinorTickSpacing(200);
        mediumSlider4.setPaintLabels(true);
        mediumSlider4.setPaintTicks(true);
        mediumSlider4.setSnapToTicks(true);
        add(mediumSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 240, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel11.setText("Washing Machine");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, 40));

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel12.setText("Air Conditioner");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, 40));

        heavySlider3.setBackground(new java.awt.Color(255, 204, 102));
        heavySlider3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        heavySlider3.setForeground(new java.awt.Color(0, 0, 102));
        heavySlider3.setMajorTickSpacing(1000);
        heavySlider3.setMaximum(5000);
        heavySlider3.setMinimum(1000);
        heavySlider3.setMinorTickSpacing(1000);
        heavySlider3.setPaintLabels(true);
        heavySlider3.setPaintTicks(true);
        heavySlider3.setSnapToTicks(true);
        add(heavySlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 240, 40));

        mediumSlider5.setBackground(new java.awt.Color(255, 204, 102));
        mediumSlider5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        mediumSlider5.setForeground(new java.awt.Color(0, 0, 102));
        mediumSlider5.setMajorTickSpacing(200);
        mediumSlider5.setMaximum(1000);
        mediumSlider5.setMinorTickSpacing(200);
        mediumSlider5.setPaintLabels(true);
        mediumSlider5.setPaintTicks(true);
        mediumSlider5.setSnapToTicks(true);
        add(mediumSlider5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 240, 40));

        mediumSlider6.setBackground(new java.awt.Color(255, 204, 102));
        mediumSlider6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        mediumSlider6.setForeground(new java.awt.Color(0, 0, 102));
        mediumSlider6.setMajorTickSpacing(200);
        mediumSlider6.setMaximum(1000);
        mediumSlider6.setMinorTickSpacing(200);
        mediumSlider6.setPaintLabels(true);
        mediumSlider6.setPaintTicks(true);
        mediumSlider6.setSnapToTicks(true);
        add(mediumSlider6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 240, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
int lowDuty = lightSlider.getValue();
int mediumDuty = heavySlider.getValue();
int heavyDuty = heavySlider.getValue();

        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);    // TODO add your handling code here:
    }//GEN-LAST:event_backJButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton3;
    private javax.swing.JSlider heavySlider;
    private javax.swing.JSlider heavySlider1;
    private javax.swing.JSlider heavySlider3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider lightSlider;
    private javax.swing.JSlider mediumSlider1;
    private javax.swing.JSlider mediumSlider2;
    private javax.swing.JSlider mediumSlider3;
    private javax.swing.JSlider mediumSlider4;
    private javax.swing.JSlider mediumSlider5;
    private javax.swing.JSlider mediumSlider6;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
