/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SignupNewUser;

import Business.Person.PersonDirectory;
import Business.SmartGrid;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Raghuram
 */
public class SignupNewUserJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private PersonDirectory personDirectory;
    private SmartGrid sg;

    /**
     * Creates new form SignupNewUser
     */
    public SignupNewUserJPanel(JPanel userProcessContainer, PersonDirectory personDirectory, SmartGrid sg) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.sg = sg;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnHUser = new javax.swing.JButton();
        btnME = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnIUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SIGNUP NEW USER");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        btnHUser.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnHUser.setText("Household User");
        btnHUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHUserActionPerformed(evt);
            }
        });
        add(btnHUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 30));

        btnME.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnME.setText("Maintenance Employee");
        btnME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEActionPerformed(evt);
            }
        });
        add(btnME, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 200, 30));

        btnBack.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 80, 30));

        btnIUser.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnIUser.setText("Industry Employee");
        btnIUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIUserActionPerformed(evt);
            }
        });
        add(btnIUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHUserActionPerformed
        HouseholdUserSignupJPanel hus = new HouseholdUserSignupJPanel(userProcessContainer, personDirectory, sg);
        userProcessContainer.add("hus", hus);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHUserActionPerformed

    private void btnMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEActionPerformed
        MaintenanceUserSignupJPanel mes = new MaintenanceUserSignupJPanel(userProcessContainer, personDirectory, sg);
        userProcessContainer.add("mes", mes);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMEActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnIUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIUserActionPerformed
        IndustryUserSignupJPanel ius = new IndustryUserSignupJPanel(userProcessContainer, personDirectory, sg);
        userProcessContainer.add("ius", ius);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHUser;
    private javax.swing.JButton btnIUser;
    private javax.swing.JButton btnME;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
