/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.IndustryEmployeeWorkArea;

import Business.Appliances.Appliance;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author Raghuram
 */
public class IndustryEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private Person person;
    private Appliance appliance;

    /**
     * Creates new form HouseHoldWorkAreaJPanel
     */
    public IndustryEmployeeWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Organization organization) {
        initComponents();
        System.out.print("Organization" + organization);
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = account;
        populateLabel();
    }

    public void populateLabel() {

        for (Person p : organization.getPersonDirectory().getPersonList()) {
            valueLabel.setText(p.getName());
           // String filename = p.getUrl();
//            ImageIcon icon = new ImageIcon(filename);
//            labelPhoto.setIcon(icon);S
            if (p.getName().equals(userAccount.getPerson().getName())) {
               
                labelPhoto.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                            new java.net.URL(p.getUrl())
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
                
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnAccess = new javax.swing.JButton();
        btnInputAppliances = new javax.swing.JButton();
        btnGenerateConsumption = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        labelPhoto = new javax.swing.JLabel();
        payEBill1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("INDUSTRY EMPLOYEE WORKAREA ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        btnAccess.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnAccess.setText("Request Access");
        btnAccess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessActionPerformed(evt);
            }
        });
        add(btnAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 240, 40));

        btnInputAppliances.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnInputAppliances.setText("Input Appliances");
        btnInputAppliances.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInputAppliances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputAppliancesActionPerformed(evt);
            }
        });
        add(btnInputAppliances, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 240, 40));

        btnGenerateConsumption.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnGenerateConsumption.setText("Consumption");
        btnGenerateConsumption.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerateConsumption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateConsumptionActionPerformed(evt);
            }
        });
        add(btnGenerateConsumption, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 240, 40));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 90, 30));
        add(labelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 160, 160));

        payEBill1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        payEBill1.setText("Sensor Input");
        payEBill1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payEBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payEBill1ActionPerformed(evt);
            }
        });
        add(payEBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 240, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessActionPerformed
        RequestAccessJPanel requestAccessJPanel = new RequestAccessJPanel(userProcessContainer, enterprise, userAccount, organization, person);
        userProcessContainer.add("requestAccessJPanel", requestAccessJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccessActionPerformed

    private void btnInputAppliancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputAppliancesActionPerformed
        for (Person p : organization.getPersonDirectory().getPersonList()) {
            if (p.getName().equals(userAccount.getPerson().getName())) {
                person = p;
            }
        }
        System.out.println("person inside " + person);
        InputAppliancesJPanel aawj = new InputAppliancesJPanel(userProcessContainer, userAccount, organization, enterprise, appliance, person);
        userProcessContainer.add("aawj", aawj);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

//         TODO add your handling code here:
    }//GEN-LAST:event_btnInputAppliancesActionPerformed

    private void btnGenerateConsumptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateConsumptionActionPerformed
        GenerateConsumptionJPanel generateConsumption = new GenerateConsumptionJPanel(userProcessContainer, userAccount, organization);
        userProcessContainer.add("generateConsumption", generateConsumption);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateConsumptionActionPerformed

    private void payEBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payEBill1ActionPerformed
        SensorInputJPanel sensorInput = new SensorInputJPanel(userProcessContainer, userAccount, organization);
        userProcessContainer.add("SensorInput", sensorInput);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);    // TODO add your handling code here:
    }//GEN-LAST:event_payEBill1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccess;
    private javax.swing.JButton btnGenerateConsumption;
    private javax.swing.JButton btnInputAppliances;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JButton payEBill1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
