/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReportGeneration;

import Business.Customer;
import Business.Employee;
import Business.EmployeeDirectory;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raghuram
 */
public class AboveTargetPriceJPanel extends javax.swing.JPanel {
private EmployeeDirectory employeeDirectory;
        private JPanel userProcessContainer;
    /**
     * Creates new form AboveTargetPriceJPanel
     */
    public AboveTargetPriceJPanel(EmployeeDirectory employeeDirectory, JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.employeeDirectory = employeeDirectory;
         populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) aboveTable.getModel();
        dtm.setRowCount(0);
        for (Employee e : employeeDirectory.getEmployeeList()) {
            Object row[] = new Object[3];
            row[0] = e;
            row[1] = e.getTargetPriceAbove();
           
            dtm.addRow(row);
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        aboveTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(aboveTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 375, 93));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aboveTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
