/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.Person;

/**
 *
 * @author Raghuram
 */
public class CreatePersonJPanel extends javax.swing.JPanel {
private Person person;
    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(Person person) {
        initComponents();
        this.person=person;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirst = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        lblMiddle = new javax.swing.JLabel();
        txtMiddle = new javax.swing.JTextField();
        lblLast = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblTown = new javax.swing.JLabel();
        txtTown = new javax.swing.JTextField();
        lblOccupation = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCreatePerson = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirst.setText("First Name");
        add(lblFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 44, -1, -1));
        add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 41, 116, -1));

        lblMiddle.setText("Middle Name");
        add(lblMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 130, -1, -1));
        add(txtMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 130, 116, -1));

        lblLast.setText("Last Name");
        add(lblLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 85, -1, -1));
        add(txtLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 82, 116, -1));

        lblDOB.setText("DOB");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 171, -1, -1));
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 168, 116, -1));

        lblAddress.setText("Street Address");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 215, -1, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 212, 116, -1));

        lblTown.setText("Town");
        add(lblTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 253, -1, -1));
        add(txtTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 250, 116, -1));

        lblOccupation.setText("Occupation");
        add(lblOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 322, -1, -1));
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 281, 116, -1));

        lblZip.setText("Zip Code");
        add(lblZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 284, -1, -1));
        add(txtOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 319, 116, -1));

        lblEmail.setText("Email Address");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 360, -1, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 357, 116, -1));

        lblArea.setText("Area Code");
        add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 401, -1, -1));
        add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 398, 116, -1));

        lblPhone.setText("Phone Number");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 439, -1, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 436, 116, -1));

        jLabel12.setText("CREATE PERSONAL DETAILS");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 11, -1, 12));

        btnCreatePerson.setText("Create");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });
        add(btnCreatePerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 474, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        person.setFirstName(txtFirst.getText());
        person.setLastName(txtLast.getText());
        person.setMiddleName(txtMiddle.getText());
        person.setDateOfBirth(Integer.parseInt(txtDOB.getText()));
        person.setStreetAddress(txtAddress.getText());
        person.setTown(txtTown.getText());
        person.setZipCode(Integer.parseInt(txtZip.getText()));
        person.setOccupation(txtOccupation.getText());
        person.setEmailAddress(txtEmail.getText());
        person.setAreaCode(Integer.parseInt(txtArea.getText()));
        person.setPhoneNumber(Integer.parseInt(txtPhone.getText()));
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnCreatePersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblMiddle;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTown;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtMiddle;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTown;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
