/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole;

import Business.Employee;
import Business.EmployeeDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Raghuram
 */
public class AddEmployee extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EmployeeDirectory employeeDirectory;

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee(JPanel userProcessContainer, EmployeeDirectory employeeDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.employeeDirectory = employeeDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEID = new javax.swing.JTextField();
        btnAddEmployee = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ADD EMPLOYEE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Employee Phone");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, 20));

        txtEPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEPhoneActionPerformed(evt);
            }
        });
        add(txtEPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 130, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Employee Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 20));

        txtEName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtENameActionPerformed(evt);
            }
        });
        add(txtEName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Employee ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 20));

        txtEID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEIDActionPerformed(evt);
            }
        });
        add(txtEID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 130, 20));

        btnAddEmployee.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnAddEmployee.setText("ADD EMPLOYEE");
        btnAddEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });
        add(btnAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 130, 30));

        btnBack.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        btnBack.setText("<<BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEPhoneActionPerformed

    private void txtENameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtENameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtENameActionPerformed

    private void txtEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEIDActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        if (txtEName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Employee Name");
            return;

        } else if (txtEID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a valid Employee ID");
            return;
        } else if (!txtEPhone.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Enter a valid Phone Number");
            return;
        }
        Employee employee = employeeDirectory.addEmployee();
        employee.setEmployeeName(txtEName.getText());
        employee.setEmployeeID(txtEID.getText());
        employee.setEmployeePhone(Integer.parseInt(txtEPhone.getText()));
        JOptionPane.showMessageDialog(null, "Employee added successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        backAction();
    }//GEN-LAST:event_btnBackActionPerformed
    private void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length - 1];
        ManageEmployee me = (ManageEmployee) c;
        me.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEID;
    private javax.swing.JTextField txtEName;
    private javax.swing.JTextField txtEPhone;
    // End of variables declaration//GEN-END:variables
}
