package UserInterface.AdminstrativeRole;

import Business.EmployeeDirectory;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mihir Mehta / Hechen Gao
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EmployeeDirectory employeeDirectory;
    private SupplierDirectory supplierDirectory;

    public AdminWorkAreaJPanel(JPanel userProcessContainer, EmployeeDirectory employeeDirectory, SupplierDirectory supplierDirectory) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
        this.employeeDirectory = employeeDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageEmployees = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnManageSuppliers1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageEmployees.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        btnManageEmployees.setText("Manage Employees >>");
        btnManageEmployees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManageEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeesActionPerformed(evt);
            }
        });
        add(btnManageEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 260, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ADMINISTRATIVE ROLE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        btnManageSuppliers1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        btnManageSuppliers1.setText("Manage Suppliers >>");
        btnManageSuppliers1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManageSuppliers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSuppliers1ActionPerformed(evt);
            }
        });
        add(btnManageSuppliers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeesActionPerformed
        ManageEmployee me = new ManageEmployee(userProcessContainer, employeeDirectory);
        userProcessContainer.add("me", me);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEmployeesActionPerformed

    private void btnManageSuppliers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSuppliers1ActionPerformed
        ManageSuppliers ms = new ManageSuppliers(userProcessContainer, supplierDirectory);
        userProcessContainer.add("ms", ms);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

// TODO add your handling code here:
    }//GEN-LAST:event_btnManageSuppliers1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManageSuppliers1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
