/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Product;

/**
 *
 * @author Raghuram
 */
public class ViewProductJPanel extends javax.swing.JPanel {

    private Product product;
    /**
     * Creates new form ViewProductJpanel
     */
    public ViewProductJPanel(Product product) {
        initComponents();
        this.product = product;
        txtProductName.setText(product.getProductName());
        txtProductPrice.setText(String.valueOf(product.getProductPrice()));
        txtProductDescription.setText(product.getProductDescription());
        txtProductQuantity.setText(String.valueOf(product.getProductQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewProductLbl = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        lblProductPrice = new javax.swing.JLabel();
        txtProductPrice = new javax.swing.JTextField();
        lblProductDescription = new javax.swing.JLabel();
        txtProductDescription = new javax.swing.JTextField();
        lblProductQuantity = new javax.swing.JLabel();
        txtProductQuantity = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewProductLbl.setText("View Product");
        add(viewProductLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 11, -1, -1));

        lblProductName.setText("Product Name");
        add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 60, -1, -1));

        txtProductName.setEnabled(false);
        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 57, 140, -1));

        lblProductPrice.setText("Product Price");
        add(lblProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 98, -1, -1));

        txtProductPrice.setEnabled(false);
        txtProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductPriceActionPerformed(evt);
            }
        });
        add(txtProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 95, 140, -1));

        lblProductDescription.setText("Product Description");
        add(lblProductDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 136, -1, -1));

        txtProductDescription.setEnabled(false);
        add(txtProductDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 133, 140, -1));

        lblProductQuantity.setText("Product Quantity");
        add(lblProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 174, -1, -1));

        txtProductQuantity.setEnabled(false);
        add(txtProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 171, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void txtProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblProductDescription;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblProductQuantity;
    private javax.swing.JTextField txtProductDescription;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtProductQuantity;
    private javax.swing.JLabel viewProductLbl;
    // End of variables declaration//GEN-END:variables
}
